# Generated by Django 2.0.3 on 2018-05-12 21:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Inicio', '0003_auto_20180512_1642'),
    ]

    operations = [
        migrations.CreateModel(
            name='Imagenesproyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeriaproyecto', models.FileField(upload_to='galeriaproyecto/')),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portafolio', models.TextField()),
                ('visualizaciones', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombreproyecto', models.CharField(blank=True, help_text='Texto de maximo 120 caracteres', max_length=120, null=True)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'imagen'), ('video', 'video')], default='imagen', max_length=20)),
                ('imagen', models.FileField(upload_to='portafolio/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Cliente')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.Portafolio')),
            ],
        ),
        migrations.AddField(
            model_name='imagenesproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Proyectos.Proyecto'),
        ),
    ]
