# Generated by Django 2.0.3 on 2018-07-29 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0002_auto_20180513_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='detalle',
            field=models.TextField(blank=True, null=True),
        ),
    ]
