# Generated by Django 2.0.3 on 2018-07-29 14:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0003_proyecto_detalle'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitas_Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visita', models.IntegerField(default=1)),
                ('proyecto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Proyectos.Proyecto', unique=True)),
            ],
            options={
                'verbose_name_plural': '4. Visitas al Proyecto',
            },
        ),
    ]
