# Generated by Django 2.0.3 on 2018-08-07 02:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0004_visitas_proyecto'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='orden',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
