# Generated by Django 2.0 on 2018-11-27 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0007_auto_20181127_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='tipo_archivo',
            field=models.CharField(choices=[('imagen', 'imagen'), ('video_vertical', 'video_vertical'), ('video', 'video')], default='imagen', max_length=20),
        ),
    ]
