# Generated by Django 2.0 on 2018-12-02 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0010_remove_proyecto_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyecto',
            name='link',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
