# Generated by Django 2.0 on 2018-12-05 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0011_proyecto_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='portafolio/'),
        ),
    ]
