# Generated by Django 2.0 on 2018-12-12 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0012_auto_20181205_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyecto',
            name='imagen',
            field=models.FileField(blank=True, help_text='imagen producto 851x315', null=True, upload_to='portafolio/'),
        ),
    ]
