# Generated by Django 2.0 on 2018-12-23 21:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0013_auto_20181212_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={},
        ),
    ]
