# Generated by Django 2.0 on 2018-12-25 01:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Proyectos', '0014_auto_20181223_1652'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='proyecto',
            options={'verbose_name_plural': '2. Proyecto'},
        ),
    ]
