# Generated by Django 2.0.3 on 2018-05-12 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(help_text='imagen de 1280*500', upload_to='blog/')),
                ('fecha', models.DateField()),
                ('titulo', models.TextField()),
                ('articulo', models.TextField()),
                ('autor', models.TextField()),
                ('imagen2', models.FileField(help_text='imagen de 1280*500', upload_to='blog/')),
            ],
            options={
                'verbose_name_plural': '3. Bloggs',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('usuario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.Blogs')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('usuario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Visitas_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visita', models.IntegerField(default=1)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.Blogs', unique=True)),
            ],
            options={
                'verbose_name_plural': '4. Visitas al Blog',
            },
        ),
        migrations.AddField(
            model_name='blogs',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.Categoria'),
        ),
    ]
