# Generated by Django 2.0.3 on 2018-05-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0002_auto_20180512_1613'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blogs',
            options={'verbose_name_plural': '2. Blogs'},
        ),
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': '1. Categorias'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'verbose_name_plural': '4. Comentarios'},
        ),
        migrations.AlterModelOptions(
            name='respuesta',
            options={'verbose_name_plural': '5. Respuestas'},
        ),
        migrations.AlterModelOptions(
            name='visitas_blog',
            options={'verbose_name_plural': '3. Visitas al Blog'},
        ),
    ]
