# Generated by Django 2.0.3 on 2018-05-14 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0003_auto_20180513_1540'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visitas_blog',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Visitas_Blog',
        ),
    ]
