# Generated by Django 2.0.3 on 2018-05-15 00:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0004_auto_20180514_1703'),
    ]

    operations = [
        migrations.CreateModel(
            name='Visitas_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visita', models.IntegerField(default=1)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Blogs.Blogs', unique=True)),
            ],
            options={
                'verbose_name_plural': '4. Visitas al Blog',
            },
        ),
    ]
