# Generated by Django 2.0.3 on 2018-05-23 01:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0005_visitas_blog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas_blog',
            name='blog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blogs.Blogs', unique=True),
        ),
    ]
