# Generated by Django 2.0 on 2018-12-01 22:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0006_auto_20180522_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visitas_blog',
            name='blog',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Blogs.Blogs'),
        ),
    ]
