# Generated by Django 2.0 on 2018-12-09 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0007_auto_20181201_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='imagen2',
            field=models.FileField(blank=True, help_text='imagen de 1280*500', null=True, upload_to='blog/'),
        ),
    ]
