# Generated by Django 2.0 on 2018-12-30 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0008_auto_20181209_1525'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='articulo',
        ),
    ]
