# Generated by Django 2.0 on 2018-12-30 03:31

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0009_remove_blogs_articulo'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogs',
            name='articulo',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
    ]
