# Generated by Django 2.0 on 2018-12-30 03:34

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blogs', '0010_blogs_articulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogs',
            name='articulo',
            field=ckeditor.fields.RichTextField(blank=True, max_length=10000, null=True),
        ),
    ]
