# Generated by Django 2.0.3 on 2018-05-12 19:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blogs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(help_text='imagen de 1280*500', upload_to='blog/')),
                ('fecha', models.DateField()),
                ('titulo', models.TextField()),
                ('articulo', models.TextField()),
                ('autor', models.TextField()),
                ('imagen2', models.FileField(help_text='imagen de 1280*500', upload_to='blog/')),
            ],
            options={
                'verbose_name_plural': '3. Bloggs',
            },
        ),
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Ciudad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ciudad', models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clasif_producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion_producto', models.CharField(blank=True, max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clasif_sub',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clasificacion_sub', models.CharField(blank=True, max_length=90, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.TextField()),
                ('sitio', models.TextField(blank=True, null=True)),
                ('logo', models.FileField(upload_to='logocliente/')),
            ],
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.TextField()),
                ('usuario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Blogs')),
            ],
        ),
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='equipo/')),
                ('nombre', models.TextField()),
                ('cargo', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('facebook', models.TextField(default='http://www.facebook.com/')),
                ('twitter', models.TextField(default='http://www.twitter.com/')),
                ('linkedin', models.TextField(default='http://www.linkedin.com/')),
            ],
        ),
        migrations.CreateModel(
            name='Frase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cita', models.TextField()),
                ('autor', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Imagenesproyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('galeriaproyecto', models.FileField(upload_to='galeriaproyecto/')),
            ],
        ),
        migrations.CreateModel(
            name='ImagenesServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='servicio/')),
                ('estado', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Infoicono',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Infoserv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.TextField(default='')),
                ('descripcion', models.TextField(default='')),
                ('infoicono', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Infoicono')),
            ],
        ),
        migrations.CreateModel(
            name='Mivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Planserv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagenplan', models.FileField(upload_to='planserv/')),
            ],
        ),
        migrations.CreateModel(
            name='Portafolio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portafolio', models.TextField()),
                ('visualizaciones', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_uno', models.TextField()),
                ('tema_dos', models.TextField()),
                ('tema_tres', models.TextField()),
                ('tema_cuatro', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_producto', models.CharField(blank=True, max_length=100, null=True)),
                ('imagen', models.ImageField(upload_to='producto/')),
                ('descripcion', models.CharField(blank=True, max_length=100, null=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=5)),
                ('clasif', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Clasif_producto')),
                ('clasif_sub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Clasif_sub')),
            ],
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proveedor', models.CharField(blank=True, max_length=100, null=True)),
                ('logo', models.FileField(upload_to='proveedor/')),
                ('detalle', models.CharField(blank=True, max_length=300, null=True)),
                ('direccicion', models.CharField(blank=True, max_length=100, null=True)),
                ('telefono', models.CharField(blank=True, max_length=100, null=True)),
                ('correo', models.CharField(blank=True, max_length=100, null=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Ciudad')),
            ],
        ),
        migrations.CreateModel(
            name='Proyecto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('nombreproyecto', models.CharField(blank=True, help_text='Texto de maximo 120 caracteres', max_length=120, null=True)),
                ('tipo_archivo', models.CharField(choices=[('imagen', 'imagen'), ('video', 'video')], default='imagen', max_length=20)),
                ('imagen', models.FileField(upload_to='portafolio/')),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Cliente')),
                ('portafolio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Portafolio')),
            ],
        ),
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('respuesta', models.TextField()),
                ('usuario', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('email', models.EmailField(max_length=254)),
                ('comentario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Comentario')),
            ],
        ),
        migrations.CreateModel(
            name='Servicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('titulo', models.TextField()),
                ('descripcion', models.TextField()),
                ('video', models.FileField(blank=True, null=True, upload_to='video/servicio')),
            ],
        ),
        migrations.CreateModel(
            name='Slider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orden', models.IntegerField()),
                ('imagen', models.FileField(help_text='imagen de 1920*529', upload_to='slider/')),
                ('titulo', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Trabajo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_subida', models.DateField(auto_now_add=True)),
                ('imagen', models.FileField(upload_to='trabajo/')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(help_text='Texo maximo de 40 caracteres', max_length=40)),
                ('video', models.FileField(blank=True, null=True, upload_to='video')),
                ('estado', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Visitas_Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visita', models.IntegerField(default=1)),
                ('blog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Blogs', unique=True)),
            ],
            options={
                'verbose_name_plural': '4. Visitas al Blog',
            },
        ),
        migrations.AddField(
            model_name='producto',
            name='proveedor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Proveedor'),
        ),
        migrations.AddField(
            model_name='planserv',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Servicio'),
        ),
        migrations.AddField(
            model_name='infoserv',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Servicio'),
        ),
        migrations.AddField(
            model_name='imagenesservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Servicio'),
        ),
        migrations.AddField(
            model_name='imagenesproyecto',
            name='proyecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Proyecto'),
        ),
        migrations.AddField(
            model_name='blogs',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Inicio.Categoria'),
        ),
    ]
