# Generated by Django 2.0.3 on 2018-05-12 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogs',
            name='categoria',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='blog',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='clasif',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='clasif_sub',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='proveedor',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='ciudad',
        ),
        migrations.RemoveField(
            model_name='respuesta',
            name='comentario',
        ),
        migrations.RemoveField(
            model_name='visitas_blog',
            name='blog',
        ),
        migrations.DeleteModel(
            name='Blogs',
        ),
        migrations.DeleteModel(
            name='Categoria',
        ),
        migrations.DeleteModel(
            name='Ciudad',
        ),
        migrations.DeleteModel(
            name='Clasif_producto',
        ),
        migrations.DeleteModel(
            name='Clasif_sub',
        ),
        migrations.DeleteModel(
            name='Comentario',
        ),
        migrations.DeleteModel(
            name='Producto',
        ),
        migrations.DeleteModel(
            name='Proveedor',
        ),
        migrations.DeleteModel(
            name='Respuesta',
        ),
        migrations.DeleteModel(
            name='Visitas_Blog',
        ),
    ]
