# Generated by Django 2.0.3 on 2018-05-12 21:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0002_auto_20180512_1607'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenesproyecto',
            name='proyecto',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='proyecto',
            name='portafolio',
        ),
        migrations.DeleteModel(
            name='Imagenesproyecto',
        ),
        migrations.DeleteModel(
            name='Portafolio',
        ),
        migrations.DeleteModel(
            name='Proyecto',
        ),
    ]
