# Generated by Django 2.0.3 on 2018-05-13 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0003_auto_20180512_1642'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='video',
        ),
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.FileField(blank=True, null=True, upload_to='servicio/'),
        ),
    ]
