# Generated by Django 2.0.3 on 2018-05-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0004_auto_20180513_0846'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicio',
            name='imagen',
        ),
    ]
