# Generated by Django 2.0.3 on 2018-05-13 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0005_remove_servicio_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='imagenesservicio',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='infoserv',
            name='infoicono',
        ),
        migrations.RemoveField(
            model_name='infoserv',
            name='servicio',
        ),
        migrations.RemoveField(
            model_name='planserv',
            name='servicio',
        ),
        migrations.DeleteModel(
            name='ImagenesServicio',
        ),
        migrations.DeleteModel(
            name='Infoicono',
        ),
        migrations.DeleteModel(
            name='Infoserv',
        ),
        migrations.DeleteModel(
            name='Planserv',
        ),
        migrations.DeleteModel(
            name='Servicio',
        ),
    ]
