# Generated by Django 2.0.3 on 2018-05-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0006_auto_20180513_0908'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Equipo',
        ),
        migrations.DeleteModel(
            name='Mivi',
        ),
        migrations.DeleteModel(
            name='Proceso',
        ),
    ]
