# Generated by Django 2.0.3 on 2018-05-23 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0007_auto_20180513_1540'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
