# Generated by Django 2.0.3 on 2018-05-23 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0008_delete_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='slider',
            name='tipo_archivo',
            field=models.CharField(choices=[('imagen', 'imagen'), ('video', 'video')], default='imagen', max_length=20),
        ),
    ]
