# Generated by Django 2.0.3 on 2018-05-23 21:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0009_slider_tipo_archivo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='slider',
            old_name='imagen',
            new_name='archivo',
        ),
    ]
