# Generated by Django 2.0.3 on 2018-08-11 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0012_cliente_orden'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='orden',
            field=models.IntegerField(default=0),
        ),
    ]
