# Generated by Django 2.0.3 on 2018-08-11 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Inicio', '0013_auto_20180811_1400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cliente',
            name='orden',
            field=models.IntegerField(),
        ),
    ]
