# Generated by Django 2.0.3 on 2018-05-13 20:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenesservicio',
            options={'verbose_name_plural': '2. Imagenes Servicio '},
        ),
        migrations.AlterModelOptions(
            name='infoicono',
            options={'verbose_name_plural': '5.Icono Info Servicio'},
        ),
        migrations.AlterModelOptions(
            name='infoserv',
            options={'verbose_name_plural': '4. Info Servicio'},
        ),
        migrations.AlterModelOptions(
            name='planserv',
            options={'verbose_name_plural': '3. Plan Servicio'},
        ),
        migrations.AlterModelOptions(
            name='servicio',
            options={'verbose_name_plural': '1. Servicio'},
        ),
    ]
