# Generated by Django 2.0.3 on 2018-05-22 20:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0002_auto_20180513_1540'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contenido_plan_branding',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brief', models.BooleanField(default=False)),
                ('nombre_marca', models.BooleanField(default=False)),
                ('creacion_logotipo', models.BooleanField(default=False)),
                ('manual_marca', models.BooleanField(default=False)),
                ('slogan', models.BooleanField(default=False)),
                ('lema', models.BooleanField(default=False)),
                ('clain', models.BooleanField(default=False)),
                ('disenio_tarjeta', models.BooleanField(default=False)),
                ('disenio_papeleria_basica', models.BooleanField(default=False)),
                ('disenio_papeleria_corpo', models.BooleanField(default=False)),
                ('disenio_sistema_uniforme', models.BooleanField(default=False)),
                ('fachada_3d', models.BooleanField(default=False)),
                ('impresion_tarjetas', models.BooleanField(default=False)),
                ('firma_email', models.BooleanField(default=False)),
                ('linea_grafica', models.BooleanField(default=False)),
                ('precioplan', models.CharField(blank=True, max_length=6, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Tipo_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan', models.CharField(blank=True, help_text=' A,B,C,D', max_length=1, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='contenido_plan_branding',
            name='tipo_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.Tipo_plan'),
        ),
    ]
