# Generated by Django 2.0.3 on 2018-05-23 01:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0004_auto_20180522_2032'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contenido_plan_branding',
            new_name='Contenido_plan',
        ),
    ]
