# Generated by Django 2.0.3 on 2018-05-23 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0005_auto_20180522_2043'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contenido_plan',
            name='brief',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='clain',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='creacion_logotipo',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='disenio_papeleria_basica',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='disenio_papeleria_corpo',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='disenio_sistema_uniforme',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='disenio_tarjeta',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='fachada_3d',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='firma_email',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='impresion_tarjetas',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='lema',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='linea_grafica',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='manual_marca',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='nombre_marca',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='precioplan',
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='slogan',
        ),
        migrations.AddField(
            model_name='contenido_plan',
            name='contenido',
            field=models.CharField(blank=True, choices=[('brief', 'brief'), ('logo', 'logo')], max_length=60, null=True),
        ),
    ]
