# Generated by Django 2.0.3 on 2018-05-23 02:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0006_auto_20180522_2053'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalle_plan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.CharField(max_length=60)),
            ],
        ),
        migrations.RemoveField(
            model_name='contenido_plan',
            name='contenido',
        ),
        migrations.AddField(
            model_name='detalle_plan',
            name='contenido',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.Contenido_plan'),
        ),
    ]
