# Generated by Django 2.0.3 on 2018-05-23 21:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0009_auto_20180523_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoServicio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='servicio/')),
            ],
        ),
        migrations.RemoveField(
            model_name='servicio',
            name='video',
        ),
        migrations.AddField(
            model_name='videoservicio',
            name='servicio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Servicios.Servicio'),
        ),
    ]
