# Generated by Django 2.0.3 on 2018-08-07 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0010_auto_20180523_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicio',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='servicio/'),
        ),
    ]
