# Generated by Django 2.0.3 on 2018-08-11 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Servicios', '0011_servicio_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='contenido_plan',
            name='planpopular',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contenido_plan',
            name='precioplan',
            field=models.CharField(blank=True, max_length=60, null=True),
        ),
    ]
