# Generated by Django 2.0.3 on 2018-08-11 18:08

import ckeditor.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Productos', '0006_auto_20180810_1859'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='caracteristicas',
            field=ckeditor.fields.RichTextField(blank=True, max_length=500, null=True),
        ),
    ]
