# Generated by Django 2.0.3 on 2018-05-13 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagen', models.FileField(upload_to='equipo/')),
                ('nombre', models.TextField()),
                ('cargo', models.TextField()),
                ('correo', models.EmailField(max_length=254)),
                ('facebook', models.TextField(default='http://www.facebook.com/')),
                ('twitter', models.TextField(default='http://www.twitter.com/')),
                ('linkedin', models.TextField(default='http://www.linkedin.com/')),
            ],
        ),
        migrations.CreateModel(
            name='Mivi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mision', models.TextField()),
                ('vision', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tema_uno', models.TextField()),
                ('tema_dos', models.TextField()),
                ('tema_tres', models.TextField()),
                ('tema_cuatro', models.TextField()),
            ],
        ),
    ]
