# Generated by Django 2.0.3 on 2018-05-15 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Experiencia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientes', models.IntegerField(max_length=4)),
                ('experiencia', models.IntegerField(max_length=2)),
                ('reconocimientos', models.IntegerField(max_length=2)),
                ('certificaciones', models.IntegerField(max_length=2)),
            ],
        ),
    ]
