# Generated by Django 2.0.3 on 2018-05-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0002_experiencia'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experiencia',
            name='certificaciones',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='clientes',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='experiencia',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='experiencia',
            name='reconocimientos',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
