# Generated by Django 2.0.3 on 2018-05-18 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0006_auto_20180516_1954'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Contacto',
            new_name='Contacto_empresa',
        ),
    ]
