# Generated by Django 2.0.3 on 2018-05-18 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0007_auto_20180518_0720'),
    ]

    operations = [
        migrations.CreateModel(
            name='Logotipo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.ImageField(upload_to='empresa/logo/')),
                ('logo_blanco', models.ImageField(upload_to='empresa/logo/')),
                ('logo_blanco2', models.ImageField(upload_to='empresa/logo/')),
                ('logo_negro', models.ImageField(upload_to='empresa/logo/')),
                ('favicon', models.ImageField(upload_to='empresa/logo/')),
            ],
        ),
        migrations.AddField(
            model_name='contacto_empresa',
            name='linkedin',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='contacto_empresa',
            name='mapa',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
