# Generated by Django 2.0.3 on 2018-05-21 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0008_auto_20180518_1034'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto_empresa',
            options={'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='logotipo',
            options={'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='mivi',
            options={'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='proceso',
            options={'verbose_name_plural': ''},
        ),
        migrations.AlterModelOptions(
            name='valores',
            options={'verbose_name_plural': ''},
        ),
        migrations.AlterField(
            model_name='contacto_empresa',
            name='telefono',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
