# Generated by Django 2.0.3 on 2018-05-22 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0009_auto_20180521_0956'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contacto_empresa',
            options={'verbose_name_plural': '7. Contácto'},
        ),
        migrations.AlterModelOptions(
            name='equipo',
            options={'verbose_name_plural': '4. Equipo de Trabajo'},
        ),
        migrations.AlterModelOptions(
            name='experiencia',
            options={'verbose_name_plural': '5.  Experiencia'},
        ),
        migrations.AlterModelOptions(
            name='logotipo',
            options={'verbose_name_plural': '1. Logotipo'},
        ),
        migrations.AlterModelOptions(
            name='mivi',
            options={'verbose_name_plural': '2. Misión / Visión'},
        ),
        migrations.AlterModelOptions(
            name='proceso',
            options={'verbose_name_plural': '6. Proceso'},
        ),
        migrations.AlterModelOptions(
            name='valores',
            options={'verbose_name_plural': '3. Valores'},
        ),
    ]
