# Generated by Django 2.0 on 2018-11-24 13:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Empresa', '0012_contacto_redes'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contacto_empresa',
            name='behance',
        ),
        migrations.RemoveField(
            model_name='contacto_empresa',
            name='facebook',
        ),
        migrations.RemoveField(
            model_name='contacto_empresa',
            name='instagram',
        ),
        migrations.RemoveField(
            model_name='contacto_empresa',
            name='linkedin',
        ),
        migrations.RemoveField(
            model_name='contacto_empresa',
            name='twitter',
        ),
        migrations.RemoveField(
            model_name='contacto_empresa',
            name='youtube',
        ),
    ]
